from typing import overload

import wx


class IconLocation(object):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, filename, num: int = 0) -> None: ...

    def GetFileName(self) -> wx._WxNameType: ...
    def GetIndex(self) -> int: ...
    def IsOk(self) -> bool: ...
    def SetFileName(self, filename: wx._WxNameType): ...
    def SetIndex(self, num) -> None: ...
    def __bool__(self) -> int: ...
    def __nonzero__(self) -> int: ...
    FileName: wx._WxNameType
    Index: int
