from typing import Any, Text

import wx.dataview

class DataViewItemObjectMapper(object):
    def __init__(self): ...
    def ItemToObject(self, item: wx.dataview.DataViewItem) -> Any: ...
    def ObjectToItem(self, obj: Any) -> wx.dataview.DataViewItem: ...
    def UseWeakRefs(self, flag: bool) -> None: ...

