import wx
import wx.dataview

class DataViewModelNotifier(object):
    def __init__(self) -> None: ...
    def Cleared(self) -> bool: ...
    def GetOwner(self) -> wx.dataview.DataViewModel: ...
    def ItemAdded(self, parent: wx.dataview.DataViewItem, item: wx.dataview.DataViewItem) -> bool: ...
    def ItemChanged(self, item: wx.dataview.DataViewItem) -> bool: ...
    def ItemDeleted(self, parent: wx.dataview.DataViewItem, item: wx.dataview.DataViewItem) -> bool: ...
    def ItemsAdded(self, parent: wx.dataview.DataViewItem, items: wx.dataview.DataViewItemArray) -> bool: ...
    def ItemsChanged(self, items: wx.dataview.DataViewItemArray) -> bool: ...
    def ItemsDeleted(self, parent: wx.dataview.DataViewItem, items: wx.dataview.DataViewItemArray) -> bool: ...
    def Resort(self) -> wx.Unknown: ...
    def SetOwner(self, owner: wx.dataview.DataViewModel) -> wx.Unknown: ...
    def ValueChanged(self, item: wx.dataview.DataViewItem, col: int) -> bool: ...
    Owner: wx.dataview.DataViewModel
