from typing import Any, MutableMapping, Optional, Text, Type

import wx.dataview

class PyDataViewModel(wx.dataview.DataViewModel, wx.dataview.DataViewItemObjectMapper):
    def __init__(self) -> None: ...
#     def GetColumnCount(self) -> int: ...
#     def GetColumnType(self, col: int) -> Type: ...
#     def GetChildren(self, parent: wx.dataview.DataViewItem, children: MutableMapping) -> int: ...
#     def IsContainer(self, item: wx.dataview.DataViewItem) -> bool: ...
#     def HasContainerColumns(self, item: wx.dataview.DataViewItem) -> bool: ...
#     def GetParent(self, item: wx.dataview.DataViewItem) -> wx.dataview.DataViewItem: ...
#     def GetValue(self, item: wx.dataview.DataViewItem, col: int) -> Any: ...
#     def GetAttr(self, item: wx.dataview.DataViewItem, col: int, attr: wx.dataview.DataViewItemAttr) -> bool: ...
#     def SetValue(self, value: Any, item: wx.dataview.DataViewItem, col: int) -> bool: ...
    ...
